name: "CI"
on:
  pull_request:
  push:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: shellcheck tests/*.sh
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix-build -A hydraJobs.release
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get toolchain version
      run: |
        c++ --version
        ld --version
        autoconf --version
    - run: |
        ./bootstrap.sh
        mkdir build && cd build
        ../configure --with-asan --with-ubsan
        make -j$(nproc) check

  glibc:
    strategy:
      fail-fast: false
      matrix:
        glibc: ["2_17", "2_28"]
        platform: ["x86_64", "i686", "ppc64le", "aarch64", "s390x"]
        exclude:
        - glibc: "2_28"
          platform: "i686"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      if: matrix.platform != 'x86_64'
      uses: docker/setup-qemu-action@v2
    - run: |
        cat <<EOF > build.sh
        set -e
        set -x
        c++ --version
        ld --version
        autoconf --version
        ./bootstrap.sh
        mkdir build && cd build
        ../configure
        make -j$(nproc) check || (cat tests/test-suite.log; exit 1)
        EOF

        docker run -v $(pwd):/gha quay.io/pypa/manylinux${{ matrix.glibc == '2_17' && '2014' || format('_{0}', matrix.glibc) }}_${{ matrix.platform }}:latest sh -ec "cd /gha && sh ./build.sh"
